name: Simple Calculator Project
run-name: Simple Calculator Project is building
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Build EXE from Python Script
        uses: Nuitka/Nuitka-Action@v0.4
        with:
          script-name: main.py
