name: Simple Calculator Project
run-name: Simple Calculator Project is building
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Python Unit Test
        uses: onichandame/python-test-action@0.0.0
        with:
          pattern: help.py
      - run: sudo apt-get update -y
      - run: echo "🍏 This job's status is ${{ job.status }}."
