name: Simple Calculator Project
run-name: Simple Calculator Project is building
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Python Unit Test
        uses: onichandame/python-test-action@0.0.0
        with:
          pattern: help.py
      - name: Build EXE from Python Script
        uses: Nuitka/Nuitka-Action@v0.4
        with:
          script-name: main.py
          onefile: true
      - run: echo "🍏 This job's status is ${{ job.status }}."
